### ISSUE TITLE
 Feature: Implement FAQ Section

### ISSUE THREAD

**Issue by andoriyaprashant** [savitore/STEAM-Celestial-Satellite-tracker-in-real-time#10]
## Description 

To enhance user experience, I propose adding a Frequently Asked Questions (FAQ) section to the STEAM app. This section will offer quick access to information on satellite tracking, Liquid Galaxy rig usage, and common troubleshooting. The goal is to empower users with easily accessible answers, streamlining support and contributing to an informed and positive app experience.

The FAQ section aims to improve user support, reducing the need for external assistance. Users will find quick solutions to common queries, fostering a sense of empowerment and satisfaction. This addition aligns with our commitment to providing a user-centric and informative app.

**Comment by yash-jain-1** [comment]
Hi Prashant, can I contribute to this issue? I am starting out with open source contributions please let me know

**Comment by savitore** [comment]
@yash-jain-1 please work on "Add Clear button to Search Field" issue. This issue is assigned to @andoriyaprashant

**Comment by andoriyaprashant** [comment]
Hello @savitore 
Please review my pull request (#12) , and if there are any changes you'd like to make, please let me know. I will try to address them as quickly as possible.
