### ISSUE TITLE
Implement CONTRIBUTING.md and CODE_OF_CONDUCT.md files

### ISSUE THREAD

**Issue by andoriyaprashant** [savitore/STEAM-Celestial-Satellite-tracker-in-real-time#13]
**Objective:**
Implement CONTRIBUTING.md and CODE_OF_CONDUCT.md files to enhance project collaboration and set community standards.

![Screenshot 2023-12-29 084114](https://github.com/savitore/STEAM-Celestial-Satellite-tracker-in-real-time/assets/121665385/f99c67e5-36d4-482f-bced-f82835af9210)

**CONTRIBUTING.md File:**

- Guide for contributors.
- Outlines procedures, coding standards, and workflow.

**CODE_OF_CONDUCT.md File:**

- Defines community behavior standards.
- Promotes a positive and inclusive environment.

**Benefits:**

Streamlined contribution process.
Establishes community standards.
Improves accessibility for contributors.

**Comment by savitore** [comment]
assigned @andoriyaprashant
