### ISSUE TITLE
 To Improve Offline User Experience by Fixing "An Error Occurred" Screen 

### ISSUE THREAD

**Issue by rkverma2022** [savitore/STEAM-Celestial-Satellite-tracker-in-real-time#16]
Addressing a UI glitch: When offline, an error screen appears with a poorly displayed "TRY AGAIN" button. Improving user experience by fixing the button layout for seamless interaction. 

![Screenshot_20240111-090952](https://github.com/savitore/STEAM-Celestial-Satellite-tracker-in-real-time/assets/112231455/3ce193ed-e71d-4739-93d3-6f2d713db1ae)

Hi, I would like to fix this issue.

**Comment by savitore** [comment]
@rkverma2022 assigned

**Comment by rkverma2022** [comment]
Issue #17  fixed, please merge it,

Thank you!
