### ISSUE TITLE
Overflow Issue in bottom bar and "#satellite" division

### ISSUE THREAD

**Issue by rkverma2022** [savitore/STEAM-Celestial-Satellite-tracker-in-real-time#20]
The bottom bar and the "#satellite" division are experiencing overflow issues, causing display inconsistencies. This may lead to an undesirable user interface and functionality concerns.

![Screenshot_20240111-191146](https://github.com/savitore/STEAM-Celestial-Satellite-tracker-in-real-time/assets/112231455/5c8f54c2-63e1-4753-ba15-126c84d36565)

Hi, 

I would like to fix it.

**Comment by savitore** [comment]
@rkverma2022 work on this.

**Comment by rkverma2022** [comment]
Thank You for assigning
