### ISSUE TITLE
Overflow issue in connect button 

### ISSUE THREAD

**Issue by andoriyaprashant** [savitore/STEAM-Celestial-Satellite-tracker-in-real-time#21]
## Description

Right overflowed by 10 pixels 

![WhatsApp Image 2024-01-11 at 22 58 57_64379215](https://github.com/savitore/STEAM-Celestial-Satellite-tracker-in-real-time/assets/121665385/9c7eceb6-2f28-4353-ad10-8ebcec923256)

I would like to work on this issue Please assign it to me
Thanks

**Comment by savitore** [comment]
assigned @andoriyaprashant , text colour of button should be white.

**Comment by andoriyaprashant** [comment]
Done @savitore Please review my pull request #22  Thank you
